pull_request_rules:
  - name: Dependabot automerge
    conditions:
      - "#approved-reviews-by>=1"
      - 'author=dependabot[bot]'
    actions:
      merge:
        method: squash
      delete_head_branch:
